export const REGISTER_REQUEST: 'REGISTER_REQUEST' = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS'
export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED'

export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS'
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED'

export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED'

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST'
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS'
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED'
export const CANCEL_GET_USER_DATA: 'CANCEL_GET_USER_DATA' = 'CANCEL_GET_USER_DATA'


export const RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST' = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED' = 'RESET_PASSWORD_FAILED'

export const RESET_PASSWORD_CODE_REQUEST: 'RESET_PASSWORD_CODE_REQUEST' = 'RESET_PASSWORD_CODE_REQUEST'
export const RESET_PASSWORD_CODE_SUCCESS: 'RESET_PASSWORD_CODE_SUCCESS' = 'RESET_PASSWORD_CODE_SUCCESS'
export const RESET_PASSWORD_CODE_FAILED: 'RESET_PASSWORD_CODE_FAILED' = 'RESET_PASSWORD_CODE_FAILED'
export const SET_NEW_PASSWORD: 'SET_NEW_PASSWORD' = 'SET_NEW_PASSWORD'
export const SET_RESTORE_CODE: 'SET_RESTORE_CODE' = 'SET_RESTORE_CODE'

export const REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST' = 'REFRESH_TOKEN_REQUEST'
export const REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS' = 'REFRESH_TOKEN_SUCCESS'
export const REFRESH_TOKEN_FAILED: 'REFRESH_TOKEN_FAILED' = 'REFRESH_TOKEN_FAILED'

export const SET_NAME: 'SET_NAME' = 'SET_NAME'
export const SET_EMAIL: 'SET_EMAIL' = 'SET_EMAIL'
export const SET_LOGIN: 'SET_LOGIN' = 'SET_LOGIN'
export const SET_PASSWORD: 'SET_PASSWORD' = 'SET_PASSWORD'
export const SET_RESTORE_EMAIL: 'SET_RESTORE_EMAIL' = 'SET_RESTORE_EMAIL'